//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtightDetection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState chkChannel1 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["chkChannel1"]));
            }
            set {
                this["chkChannel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checked")]
        public global::System.Windows.Forms.CheckState chkChannel2 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["chkChannel2"]));
            }
            set {
                this["chkChannel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState chkChannel3 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["chkChannel3"]));
            }
            set {
                this["chkChannel3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unchecked")]
        public global::System.Windows.Forms.CheckState chkChannel4 {
            get {
                return ((global::System.Windows.Forms.CheckState)(this["chkChannel4"]));
            }
            set {
                this["chkChannel4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel1PassQuantity {
            get {
                return ((string)(this["txtChannel1PassQuantity"]));
            }
            set {
                this["txtChannel1PassQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel2PassQuantity {
            get {
                return ((string)(this["txtChannel2PassQuantity"]));
            }
            set {
                this["txtChannel2PassQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel3PassQuantity {
            get {
                return ((string)(this["txtChannel3PassQuantity"]));
            }
            set {
                this["txtChannel3PassQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel4PassQuantity {
            get {
                return ((string)(this["txtChannel4PassQuantity"]));
            }
            set {
                this["txtChannel4PassQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel1NGQuantity {
            get {
                return ((string)(this["txtChannel1NGQuantity"]));
            }
            set {
                this["txtChannel1NGQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel2NGQuantity {
            get {
                return ((string)(this["txtChannel2NGQuantity"]));
            }
            set {
                this["txtChannel2NGQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel3NGQuantity {
            get {
                return ((string)(this["txtChannel3NGQuantity"]));
            }
            set {
                this["txtChannel3NGQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel4NGQuantity {
            get {
                return ((string)(this["txtChannel4NGQuantity"]));
            }
            set {
                this["txtChannel4NGQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel1TotalQuantity {
            get {
                return ((string)(this["txtChannel1TotalQuantity"]));
            }
            set {
                this["txtChannel1TotalQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel2TotalQuantity {
            get {
                return ((string)(this["txtChannel2TotalQuantity"]));
            }
            set {
                this["txtChannel2TotalQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel3TotalQuantity {
            get {
                return ((string)(this["txtChannel3TotalQuantity"]));
            }
            set {
                this["txtChannel3TotalQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtChannel4TotalQuantity {
            get {
                return ((string)(this["txtChannel4TotalQuantity"]));
            }
            set {
                this["txtChannel4TotalQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string txtPassword {
            get {
                return ((string)(this["txtPassword"]));
            }
            set {
                this["txtPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string txtInflationTime {
            get {
                return ((string)(this["txtInflationTime"]));
            }
            set {
                this["txtInflationTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string txtBalanceTime {
            get {
                return ((string)(this["txtBalanceTime"]));
            }
            set {
                this["txtBalanceTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string txtDetectionTime {
            get {
                return ((string)(this["txtDetectionTime"]));
            }
            set {
                this["txtDetectionTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string txtExhaustTime {
            get {
                return ((string)(this["txtExhaustTime"]));
            }
            set {
                this["txtExhaustTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string txtAlarmPressure {
            get {
                return ((string)(this["txtAlarmPressure"]));
            }
            set {
                this["txtAlarmPressure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string txtEquivalentVolume {
            get {
                return ((string)(this["txtEquivalentVolume"]));
            }
            set {
                this["txtEquivalentVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string txtStartDelayTime {
            get {
                return ((string)(this["txtStartDelayTime"]));
            }
            set {
                this["txtStartDelayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("差压判断")]
        public string lblJudgmentMode {
            get {
                return ((string)(this["lblJudgmentMode"]));
            }
            set {
                this["lblJudgmentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("差压式")]
        public string lblPressureDetectionType {
            get {
                return ((string)(this["lblPressureDetectionType"]));
            }
            set {
                this["lblPressureDetectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正压")]
        public string lblPressureSourceType {
            get {
                return ((string)(this["lblPressureSourceType"]));
            }
            set {
                this["lblPressureSourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color btnJudgmentModeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["btnJudgmentModeBackColor"]));
            }
            set {
                this["btnJudgmentModeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color btnPressureDetectionTypeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["btnPressureDetectionTypeBackColor"]));
            }
            set {
                this["btnPressureDetectionTypeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color btnPressureSourceTypeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["btnPressureSourceTypeBackColor"]));
            }
            set {
                this["btnPressureSourceTypeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string txtDifferentialPressureJudgmentValue {
            get {
                return ((string)(this["txtDifferentialPressureJudgmentValue"]));
            }
            set {
                this["txtDifferentialPressureJudgmentValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string txtLeakRate {
            get {
                return ((string)(this["txtLeakRate"]));
            }
            set {
                this["txtLeakRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string txtDirectPressureJudgmentValue {
            get {
                return ((string)(this["txtDirectPressureJudgmentValue"]));
            }
            set {
                this["txtDirectPressureJudgmentValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string txtDetectionDelayTime {
            get {
                return ((string)(this["txtDetectionDelayTime"]));
            }
            set {
                this["txtDetectionDelayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string txtDifferentialPressureCorrectionValue {
            get {
                return ((string)(this["txtDifferentialPressureCorrectionValue"]));
            }
            set {
                this["txtDifferentialPressureCorrectionValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2")]
        public string cbxSerialPort1 {
            get {
                return ((string)(this["cbxSerialPort1"]));
            }
            set {
                this["cbxSerialPort1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int cbxBaudRate1 {
            get {
                return ((int)(this["cbxBaudRate1"]));
            }
            set {
                this["cbxBaudRate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int cbxDataBits1 {
            get {
                return ((int)(this["cbxDataBits1"]));
            }
            set {
                this["cbxDataBits1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Even")]
        public global::System.IO.Ports.Parity cbxParity1 {
            get {
                return ((global::System.IO.Ports.Parity)(this["cbxParity1"]));
            }
            set {
                this["cbxParity1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits cbxStopBit1 {
            get {
                return ((global::System.IO.Ports.StopBits)(this["cbxStopBit1"]));
            }
            set {
                this["cbxStopBit1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string cbxSerialPort2 {
            get {
                return ((string)(this["cbxSerialPort2"]));
            }
            set {
                this["cbxSerialPort2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int cbxBaudRate2 {
            get {
                return ((int)(this["cbxBaudRate2"]));
            }
            set {
                this["cbxBaudRate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int cbxDataBits2 {
            get {
                return ((int)(this["cbxDataBits2"]));
            }
            set {
                this["cbxDataBits2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Even")]
        public global::System.IO.Ports.Parity cbxParity2 {
            get {
                return ((global::System.IO.Ports.Parity)(this["cbxParity2"]));
            }
            set {
                this["cbxParity2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits cbxStopBit2 {
            get {
                return ((global::System.IO.Ports.StopBits)(this["cbxStopBit2"]));
            }
            set {
                this["cbxStopBit2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42, 41")]
        public global::System.Drawing.Point lblJudgmentModeLocation {
            get {
                return ((global::System.Drawing.Point)(this["lblJudgmentModeLocation"]));
            }
            set {
                this["lblJudgmentModeLocation"] = value;
            }
        }
    }
}
